name: Update Reports

on:
  schedule:
    - cron: '0 11 * * *'   # 09:00 UTC daily
  workflow_dispatch:

jobs:
  update-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory
        run: mkdir -p data
        working-directory: generator

      # Restore the last cached version of data.json if available
      - name: Restore cached data.json (if available)
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: generator/data/data.json
          key: data-json
          restore-keys: |
            data-json

      # Check if data.json was restored
      - name: Check if data.json exists
        id: check_data
        run: |
          if [ -f "generator/data/data.json" ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      # Download fallback from the latest release if cache is not found
      - name: Download fallback from latest release if cache is not found
        if: steps.check_data.outputs.found == 'false'
        run: |
          echo "No cached version found. Looking for data.json in a GitHub release..."
          releases=$(curl -s https://api.github.com/repos/thunderbird/webext-reports/releases)

          for url in $(echo "$releases" | jq -r '.[].assets[]? | select(.name == "data.json") | .browser_download_url'); do
            echo "Found data.json at: $url"
            curl -L -o generator/data/data.json "$url"
            echo "Download successful."
            exit 0
          done

          echo "No data.json found in any release."
          exit 1

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: generator

      # Fetch updated add-ons from ATN and build reports
      - name: Fetch updated add-ons from ATN and build reports
        run: |
          node get_addon_data.js
          node build_reports.js
        working-directory: generator

      # Delete the cache, so we can update it
      - name: Delete Previous Cache
        if: ${{ steps.cache-restore.outputs.cache-hit == 'true' }}
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "data-json" --confirm
          
      # Update the cache with the new data.json after processing
      - name: Update cache with new data.json
        uses: actions/cache@v3
        with:
          path: generator/data/data.json
          key: data-json

      # Check for changes in reports
      - name: Check for changes in reports
        id: git-check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      # Commit and push changes
      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "Update reports"
          git push origin
